name: CI

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install packages
      run: npm install

    - name: compile
      run: npm run compile

    - name: test
      run: npm run test:ci
